### ISSUE TITLE
search box not working

### ISSUE THREAD

**Issue by nrc** [nrc/rustw#185]

**Comment by chrisha88** [comment]
Hi we are having an issue with the search option not working. Please see attached error log of the browser.
![screenshot from 2018-03-02 10-41-07](https://user-images.githubusercontent.com/33055856/36884418-f5bbe55a-1e06-11e8-9095-a58627b338db.png)

**Comment by chrisha88** [comment]
Got the below error in the panel when trying to reindex elastic search using 

> node database/reindex_elastic.js

> `Error: Cannot find module '../../../../app/api/config/elasticIndexes'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/dell/uwazi/app/api/search/search.js:1:1)
    at Module._compile (module.js:570:32)
    at loader (/home/dell/uwazi/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/home/dell/uwazi/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/dell/uwazi/database/reset_elastic_index.js:3:1)
    at Module._compile (module.js:570:32)
    at loader (/home/dell/uwazi/node_modules/babel-register/lib/node.js:144:5)
`
