### ISSUE TITLE
Rustw fails to build with rustc version 1.12.0-dev (07b3ac363 2016-07-14)

### ISSUE THREAD

**Issue by DanielJCampbell** [nrc/rustw#86]
Attempted to build Rustw with command 'cargo build --release', failed with a compiler panic with the following backtrace:

```
thread 'rustc' panicked at 'idents with different contexts are compared with operator '==': String#0, Config#2443.', src/libsyntax/ast.rs:116


stack backtrace:
   1:     0x7ff746371c58 - std::sys::backtrace::tracing::imp::write::hf504bc08f2a3011f
                        at /am/state-opera/home1/campbedani3/git/rust/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:42
   2:     0x7ff7463a77c1 - std::panicking::default_hook::_{{closure}}::h49b28af2d05b6140
                        at /am/state-opera/home1/campbedani3/git/rust/src/libstd/panicking.rs:211
   3:     0x7ff74639b56f - std::panicking::default_hook::hf5d79ad4f1ead81e
                        at /am/state-opera/home1/campbedani3/git/rust/src/libstd/panicking.rs:220
   4:     0x7ff74639bd6c - std::panicking::rust_panic_with_hook::h9a3925e37821d434
                        at /am/state-opera/home1/campbedani3/git/rust/src/libstd/panicking.rs:370
   5:     0x7ff74639baf7 - std::panicking::begin_panic::h240b4915cec4a07c
                        at /am/state-opera/home1/campbedani3/git/rust/src/libstd/panicking.rs:328
   6:     0x7ff74639b9b4 - std::panicking::begin_panic_fmt::hcfb5c8e1936587e5
                        at /am/state-opera/home1/campbedani3/git/rust/src/libstd/panicking.rs:312
   7:     0x7ff73abadcbf - _<syntax..ast..Ident as core..cmp..PartialEq>::eq::hddde303841e27cc9
                        at /am/state-opera/home1/campbedani3/git/rust/<std macros>:8
   8:     0x7ff736e96084 - syntax::visit::walk_ty::h34a975422fd5e09c
   9:     0x7ff736efa4b6 - serde_codegen::ser::serialize_item::h077e0ae3c28fee50
  10:     0x7ff736e7609c - _<F as syntax..ext..base..MultiItemDecorator>::expand::hf3a5fdce1d141364
  11:     0x7ff73ae1be84 - syntax::ext::expand::expand_annotatable::hd8446612abc56728
                        at /am/state-opera/home1/campbedani3/git/rust/src/libsyntax/ext/expand.rs:773
  12:     0x7ff73ae60cf2 - syntax::ext::expand::expand_annotatable::_{{closure}}::h8b9705652f220591
                        at /am/state-opera/home1/campbedani3/git/rust/src/libsyntax/ext/expand.rs:786
  13:     0x7ff73aa51360 - core::ops::impls::_<impl core..ops..FnOnce<A> for &'a mut F>::call_once::hd18bb8529f767ae1
                        at /am/state-opera/home1/campbedani3/git/rust/src/libcore/ops.rs:1988
  14:     0x7ff73a9d685f - _<core..option..Option<T>>::map::h877db7e06b511374
                        at /am/state-opera/home1/campbedani3/git/rust/src/libcore/option.rs:385
  15:     0x7ff73ab22ca5 - _<core..iter..FlatMap<I, U, F> as core..iter..iterator..Iterator>::next::h7de1e15fde4d8fb9
                        at /am/state-opera/home1/campbedani3/git/rust/src/libcore/iter/mod.rs:1597
  16:     0x7ff73ab31fb9 - _<syntax..util..small_vector..SmallVector<T> as core..iter..traits..Extend<T>>::extend::h90fd1f2dfdf476f8
                        at /am/state-opera/home1/campbedani3/git/rust/src/libsyntax/util/small_vector.rs:52
  17:     0x7ff73ab2de47 - _<syntax..util..small_vector..SmallVector<T> as core..iter..traits..FromIterator<T>>::from_iter::h5fd44da0e2e73a01
                        at /am/state-opera/home1/campbedani3/git/rust/src/libsyntax/util/small_vector.rs:45
  18:     0x7ff73aa65b8e - core::iter::iterator::Iterator::collect::h4bde26ee937f0a80
                        at /am/state-opera/home1/campbedani3/git/rust/src/libcore/iter/iterator.rs:1207
  19:     0x7ff73ae1c0ad - syntax::ext::expand::expand_annotatable::hd8446612abc56728
                        at /am/state-opera/home1/campbedani3/git/rust/src/libsyntax/ext/expand.rs:786
  20:     0x7ff73ae60cf2 - syntax::ext::expand::expand_annotatable::_{{closure}}::h8b9705652f220591
                        at /am/state-opera/home1/campbedani3/git/rust/src/libsyntax/ext/expand.rs:786
  21:     0x7ff73aa51360 - core::ops::impls::_<impl core..ops..FnOnce<A> for &'a mut F>::call_once::hd18bb8529f767ae1
                        at /am/state-opera/home1/campbedani3/git/rust/src/libcore/ops.rs:1988
  22:     0x7ff73a9d685f - _<core..option..Option<T>>::map::h877db7e06b511374
                        at /am/state-opera/home1/campbedani3/git/rust/src/libcore/option.rs:385
  23:     0x7ff73ab22ca5 - _<core..iter..FlatMap<I, U, F> as core..iter..iterator..Iterator>::next::h7de1e15fde4d8fb9
                        at /am/state-opera/home1/campbedani3/git/rust/src/libcore/iter/mod.rs:1597
  24:     0x7ff73ab31fb9 - _<syntax..util..small_vector..SmallVector<T> as core..iter..traits..Extend<T>>::extend::h90fd1f2dfdf476f8
                        at /am/state-opera/home1/campbedani3/git/rust/src/libsyntax/util/small_vector.rs:52
  25:     0x7ff73ab2de47 - _<syntax..util..small_vector..SmallVector<T> as core..iter..traits..FromIterator<T>>::from_iter::h5fd44da0e2e73a01
                        at /am/state-opera/home1/campbedani3/git/rust/src/libsyntax/util/small_vector.rs:45
  26:     0x7ff73aa65b8e - core::iter::iterator::Iterator::collect::h4bde26ee937f0a80
                        at /am/state-opera/home1/campbedani3/git/rust/src/libcore/iter/iterator.rs:1207
  27:     0x7ff73ae1c0ad - syntax::ext::expand::expand_annotatable::hd8446612abc56728
                        at /am/state-opera/home1/campbedani3/git/rust/src/libsyntax/ext/expand.rs:786
  28:     0x7ff73ae60cf2 - syntax::ext::expand::expand_annotatable::_{{closure}}::h8b9705652f220591
                        at /am/state-opera/home1/campbedani3/git/rust/src/libsyntax/ext/expand.rs:786
  29:     0x7ff73aa51360 - core::ops::impls::_<impl core..ops..FnOnce<A> for &'a mut F>::call_once::hd18bb8529f767ae1
                        at /am/state-opera/home1/campbedani3/git/rust/src/libcore/ops.rs:1988
  30:     0x7ff73a9d685f - _<core..option..Option<T>>::map::h877db7e06b511374
                        at /am/state-opera/home1/campbedani3/git/rust/src/libcore/option.rs:385
  31:     0x7ff73ab22ca5 - _<core..iter..FlatMap<I, U, F> as core..iter..iterator..Iterator>::next::h7de1e15fde4d8fb9
                        at /am/state-opera/home1/campbedani3/git/rust/src/libcore/iter/mod.rs:1597
  32:     0x7ff73ab31fb9 - _<syntax..util..small_vector..SmallVector<T> as core..iter..traits..Extend<T>>::extend::h90fd1f2dfdf476f8
                        at /am/state-opera/home1/campbedani3/git/rust/src/libsyntax/util/small_vector.rs:52
  33:     0x7ff73ab2de47 - _<syntax..util..small_vector..SmallVector<T> as core..iter..traits..FromIterator<T>>::from_iter::h5fd44da0e2e73a01
                        at /am/state-opera/home1/campbedani3/git/rust/src/libsyntax/util/small_vector.rs:45
  34:     0x7ff73aa65b8e - core::iter::iterator::Iterator::collect::h4bde26ee937f0a80
                        at /am/state-opera/home1/campbedani3/git/rust/src/libcore/iter/iterator.rs:1207
  35:     0x7ff73ae1c0ad - syntax::ext::expand::expand_annotatable::hd8446612abc56728
                        at /am/state-opera/home1/campbedani3/git/rust/src/libsyntax/ext/expand.rs:786
  36:     0x7ff73ae1843c - syntax::ext::expand::expand_item::h457ff37aeb19c58f
                        at /am/state-opera/home1/campbedani3/git/rust/src/libsyntax/ext/expand.rs:397
  37:     0x7ff73ae1ec78 - _<syntax..ext..expand..MacroExpander<'a, 'b> as syntax..fold..Folder>::fold_item::h4389e6b7f02d906b
                        at /am/state-opera/home1/campbedani3/git/rust/src/libsyntax/ext/expand.rs:1027
  38:     0x7ff73ae5f3db - _<syntax..util..small_vector..SmallVector<syntax..ptr..P<syntax..ast..Item>> as syntax..ext..expand..MacroGenerable>::fold_with::_{{closure}}::h6a9da67fcde1b6aa
                        at /am/state-opera/home1/campbedani3/git/rust/src/libsyntax/ext/expand.rs:69
  39:     0x7ff73aa504b5 - core::ops::impls::_<impl core..ops..FnOnce<A> for &'a mut F>::call_once::h837441e109893f34
                        at /am/state-opera/home1/campbedani3/git/rust/src/libcore/ops.rs:1988
  40:     0x7ff73a9e2128 - _<core..option..Option<T>>::map::hf9fcb61b6203970e
                        at /am/state-opera/home1/campbedani3/git/rust/src/libcore/option.rs:385
  41:     0x7ff73ab2191d - _<core..iter..FlatMap<I, U, F> as core..iter..iterator..Iterator>::next::h0ce640e1164d1d18
                        at /am/state-opera/home1/campbedani3/git/rust/src/libcore/iter/mod.rs:1597
  42:     0x7ff73ab2f81c - _<syntax..util..small_vector..SmallVector<T> as core..iter..traits..Extend<T>>::extend::h0380e538024cd000
                        at /am/state-opera/home1/campbedani3/git/rust/src/libsyntax/util/small_vector.rs:52
  43:     0x7ff73ab2ead7 - _<syntax..util..small_vector..SmallVector<T> as core..iter..traits..FromIterator<T>>::from_iter::hc6ba285178e260f4
                        at /am/state-opera/home1/campbedani3/git/rust/src/libsyntax/util/small_vector.rs:45
  44:     0x7ff73aa669fe - core::iter::iterator::Iterator::collect::h852e129ea8f45e8d
                        at /am/state-opera/home1/campbedani3/git/rust/src/libcore/iter/iterator.rs:1207
  45:     0x7ff73ae0d52b - _<syntax..util..small_vector..SmallVector<syntax..ptr..P<syntax..ast..Item>> as syntax..ext..expand..MacroGenerable>::fold_with::hc9c24844e6c3acaa
                        at /am/state-opera/home1/campbedani3/git/rust/src/libsyntax/ext/expand.rs:69
  46:     0x7ff73aeb7f33 - syntax::ext::expand::MacroExpander::new::_{{closure}}::h51c961e18a38cf7c
                        at /am/state-opera/home1/campbedani3/git/rust/src/libsyntax/ext/expand.rs:924
  47:     0x7ff73ae0d7ac - _<syntax..util..small_vector..SmallVector<syntax..ptr..P<syntax..ast..Item>> as syntax..ext..expand..MacroGenerable>::expand_with::h37346091d64f0dba
                        at /am/state-opera/home1/campbedani3/git/rust/src/libsyntax/ext/expand.rs:77
  48:     0x7ff73ae1218e - syntax::ext::expand::expand_mac_invoc::h452922c8868635d7
                        at /am/state-opera/home1/campbedani3/git/rust/src/libsyntax/ext/expand.rs:342
  49:     0x7ff73aeaff64 - syntax::ext::expand::expand_multi_modified::_{{closure}}::haf4672c57f6042f3
                        at /am/state-opera/home1/campbedani3/git/rust/src/libsyntax/ext/expand.rs:703
  50:     0x7ff73ad4086f - _<syntax..ptr..P<T>>::and_then::h06d980d06d80ee72
                        at /am/state-opera/home1/campbedani3/git/rust/src/libsyntax/ptr.rs:66
  51:     0x7ff73ae1b273 - syntax::ext::expand::expand_multi_modified::h076d1dfd2d8f43b1
                        at /am/state-opera/home1/campbedani3/git/rust/src/libsyntax/ext/expand.rs:701
  52:     0x7ff73ae1b995 - syntax::ext::expand::expand_annotatable::hd8446612abc56728
                        at /am/state-opera/home1/campbedani3/git/rust/src/libsyntax/ext/expand.rs:756
  53:     0x7ff73ae1843c - syntax::ext::expand::expand_item::h457ff37aeb19c58f
                        at /am/state-opera/home1/campbedani3/git/rust/src/libsyntax/ext/expand.rs:397
  54:     0x7ff73ae1ec78 - _<syntax..ext..expand..MacroExpander<'a, 'b> as syntax..fold..Folder>::fold_item::h4389e6b7f02d906b
                        at /am/state-opera/home1/campbedani3/git/rust/src/libsyntax/ext/expand.rs:1027
  55:     0x7ff73ae8327b - syntax::fold::noop_fold_mod::_{{closure}}::hfc8f75d570c45975
                        at /am/state-opera/home1/campbedani3/git/rust/src/libsyntax/fold.rs:962
  56:     0x7ff73ab96fed - _<collections..vec..Vec<T> as syntax..util..move_map..MoveMap<T>>::move_flat_map::hd13b5abbddb4dcf7
                        at /am/state-opera/home1/campbedani3/git/rust/src/libsyntax/util/move_map.rs:38
  57:     0x7ff73ac6063c - syntax::fold::noop_fold_mod::h28eb0cf134e63a35
                        at /am/state-opera/home1/campbedani3/git/rust/src/libsyntax/fold.rs:962
  58:     0x7ff73ac1f806 - syntax::fold::Folder::fold_mod::h889e269c27ec8b9d
                        at /am/state-opera/home1/campbedani3/git/rust/src/libsyntax/fold.rs:127
  59:     0x7ff73ac522e4 - syntax::fold::noop_fold_item_kind::h377400524a4759cb
                        at /am/state-opera/home1/campbedani3/git/rust/src/libsyntax/fold.rs:859
  60:     0x7ff73ae18652 - syntax::ext::expand::expand_item_kind::h881ebe117c286ebf
                        at /am/state-opera/home1/campbedani3/git/rust/src/libsyntax/ext/expand.rs:411
  61:     0x7ff73ae1f2e4 - _<syntax..ext..expand..MacroExpander<'a, 'b> as syntax..fold..Folder>::fold_item_kind::h09002fbbc408587f
                        at /am/state-opera/home1/campbedani3/git/rust/src/libsyntax/ext/expand.rs:1033
  62:     0x7ff73ac65184 - syntax::fold::noop_fold_item_simple::h9addaee71c594156
                        at /am/state-opera/home1/campbedani3/git/rust/src/libsyntax/fold.rs:1018
  63:     0x7ff73ac1b6e4 - syntax::fold::Folder::fold_item_simple::hdd05bbcc0d49a88b
                        at /am/state-opera/home1/campbedani3/git/rust/src/libsyntax/fold.rs:67
  64:     0x7ff73ae9b59f - syntax::fold::noop_fold_item::_{{closure}}::hcb349f961109d9e9
                        at /am/state-opera/home1/campbedani3/git/rust/src/libsyntax/fold.rs:1011
  65:     0x7ff73ad41e5d - _<syntax..ptr..P<T>>::map::h06eaa2260c3ddaf7
                        at /am/state-opera/home1/campbedani3/git/rust/src/libsyntax/ptr.rs:80
  66:     0x7ff73ac6394f - syntax::fold::noop_fold_item::h55d5c093e4c58c27
                        at /am/state-opera/home1/campbedani3/git/rust/src/libsyntax/fold.rs:1011
  67:     0x7ff73ae1b4d8 - syntax::ext::expand::expand_multi_modified::h076d1dfd2d8f43b1
                        at /am/state-opera/home1/campbedani3/git/rust/src/libsyntax/ext/expand.rs:717
  68:     0x7ff73ae1b995 - syntax::ext::expand::expand_annotatable::hd8446612abc56728
                        at /am/state-opera/home1/campbedani3/git/rust/src/libsyntax/ext/expand.rs:756
  69:     0x7ff73ae1843c - syntax::ext::expand::expand_item::h457ff37aeb19c58f
                        at /am/state-opera/home1/campbedani3/git/rust/src/libsyntax/ext/expand.rs:397
  70:     0x7ff73ae1efe4 - _<syntax..ext..expand..MacroExpander<'a, 'b> as syntax..fold..Folder>::fold_item::h4389e6b7f02d906b
                        at /am/state-opera/home1/campbedani3/git/rust/src/libsyntax/ext/expand.rs:1022
  71:     0x7ff73ae8327b - syntax::fold::noop_fold_mod::_{{closure}}::hfc8f75d570c45975
                        at /am/state-opera/home1/campbedani3/git/rust/src/libsyntax/fold.rs:962
  72:     0x7ff73ab96fed - _<collections..vec..Vec<T> as syntax..util..move_map..MoveMap<T>>::move_flat_map::hd13b5abbddb4dcf7
                        at /am/state-opera/home1/campbedani3/git/rust/src/libsyntax/util/move_map.rs:38
  73:     0x7ff73ac6063c - syntax::fold::noop_fold_mod::h28eb0cf134e63a35
                        at /am/state-opera/home1/campbedani3/git/rust/src/libsyntax/fold.rs:962
  74:     0x7ff73ac1f806 - syntax::fold::Folder::fold_mod::h889e269c27ec8b9d
                        at /am/state-opera/home1/campbedani3/git/rust/src/libsyntax/fold.rs:127
  75:     0x7ff73ac522e4 - syntax::fold::noop_fold_item_kind::h377400524a4759cb
                        at /am/state-opera/home1/campbedani3/git/rust/src/libsyntax/fold.rs:859
  76:     0x7ff73ae18652 - syntax::ext::expand::expand_item_kind::h881ebe117c286ebf
                        at /am/state-opera/home1/campbedani3/git/rust/src/libsyntax/ext/expand.rs:411
  77:     0x7ff73ae1f2e4 - _<syntax..ext..expand..MacroExpander<'a, 'b> as syntax..fold..Folder>::fold_item_kind::h09002fbbc408587f
                        at /am/state-opera/home1/campbedani3/git/rust/src/libsyntax/ext/expand.rs:1033
  78:     0x7ff73ac65184 - syntax::fold::noop_fold_item_simple::h9addaee71c594156
                        at /am/state-opera/home1/campbedani3/git/rust/src/libsyntax/fold.rs:1018
  79:     0x7ff73ac1b6e4 - syntax::fold::Folder::fold_item_simple::hdd05bbcc0d49a88b
                        at /am/state-opera/home1/campbedani3/git/rust/src/libsyntax/fold.rs:67
  80:     0x7ff73ae9b59f - syntax::fold::noop_fold_item::_{{closure}}::hcb349f961109d9e9
                        at /am/state-opera/home1/campbedani3/git/rust/src/libsyntax/fold.rs:1011
  81:     0x7ff73ad41e5d - _<syntax..ptr..P<T>>::map::h06eaa2260c3ddaf7
                        at /am/state-opera/home1/campbedani3/git/rust/src/libsyntax/ptr.rs:80
  82:     0x7ff73ac6394f - syntax::fold::noop_fold_item::h55d5c093e4c58c27
                        at /am/state-opera/home1/campbedani3/git/rust/src/libsyntax/fold.rs:1011
  83:     0x7ff73ae1b4d8 - syntax::ext::expand::expand_multi_modified::h076d1dfd2d8f43b1
                        at /am/state-opera/home1/campbedani3/git/rust/src/libsyntax/ext/expand.rs:717
  84:     0x7ff73ae1b995 - syntax::ext::expand::expand_annotatable::hd8446612abc56728
                        at /am/state-opera/home1/campbedani3/git/rust/src/libsyntax/ext/expand.rs:756
  85:     0x7ff73ae1843c - syntax::ext::expand::expand_item::h457ff37aeb19c58f
                        at /am/state-opera/home1/campbedani3/git/rust/src/libsyntax/ext/expand.rs:397
  86:     0x7ff73ae1efe4 - _<syntax..ext..expand..MacroExpander<'a, 'b> as syntax..fold..Folder>::fold_item::h4389e6b7f02d906b
                        at /am/state-opera/home1/campbedani3/git/rust/src/libsyntax/ext/expand.rs:1022
  87:     0x7ff73ac6307a - syntax::fold::noop_fold_crate::hd7c3fa998582df64
                        at /am/state-opera/home1/campbedani3/git/rust/src/libsyntax/fold.rs:970
  88:     0x7ff73ae1e954 - _<syntax..ext..expand..MacroExpander<'a, 'b> as syntax..fold..Folder>::fold_crate::hc7020302cbdbf888
                        at /am/state-opera/home1/campbedani3/git/rust/src/libsyntax/ext/expand.rs:989
  89:     0x7ff73ae20620 - syntax::ext::expand::expand_crate::h9b29ec58b7166380
                        at /am/state-opera/home1/campbedani3/git/rust/src/libsyntax/ext/expand.rs:1147
  90:     0x7ff746d83a1e - rustc_driver::driver::phase_2_configure_and_expand::_{{closure}}::h5c397c99b1ec3879
                        at /am/state-opera/home1/campbedani3/git/rust/src/librustc_driver/driver.rs:681
  91:     0x7ff746b1c46d - rustc::util::common::time::hfdd2b9f9ac719299
                        at /am/state-opera/home1/campbedani3/git/rust/src/librustc/util/common.rs:38
  92:     0x7ff746d48989 - rustc_driver::driver::phase_2_configure_and_expand::hecd5152cdf8e1dda
                        at /am/state-opera/home1/campbedani3/git/rust/src/librustc_driver/driver.rs:641
  93:     0x7ff746d44200 - rustc_driver::driver::compile_input::h2d1b58b831f06a86
                        at /am/state-opera/home1/campbedani3/git/rust/src/librustc_driver/driver.rs:119
  94:     0x7ff746d5abd6 - rustc_driver::run_compiler_with_file_loader::h2fbe14e8fe31c022
                        at /am/state-opera/home1/campbedani3/git/rust/src/librustc_driver/lib.rs:220
  95:     0x7ff746d59b48 - rustc_driver::run_compiler::h833483649bdaa9c3
                        at /am/state-opera/home1/campbedani3/git/rust/src/librustc_driver/lib.rs:157
  96:     0x7ff746dbc645 - rustc_driver::run::_{{closure}}::hf976882a071eba86
                        at /am/state-opera/home1/campbedani3/git/rust/src/librustc_driver/lib.rs:135
  97:     0x7ff746db7411 - rustc_driver::monitor::_{{closure}}::hd347b359cf4c5640
                        at /am/state-opera/home1/campbedani3/git/rust/src/librustc_driver/lib.rs:1043
  98:     0x7ff746d1a1a9 - _<std..panic..AssertUnwindSafe<F> as core..ops..FnOnce<()>>::call_once::h3217330547d1a729
                        at /am/state-opera/home1/campbedani3/git/rust/src/libstd/panic.rs:256
  99:     0x7ff746d73e73 - std::panicking::try::_{{closure}}::_{{closure}}::h4767e083ebe96610
  100:     0x7ff746a5b1c4 - std::panicking::try::call::hd16aacc09eeeaf9e
                        at /am/state-opera/home1/campbedani3/git/rust/src/libstd/panicking.rs:272
 ... <frames omitted>
```

**Comment by nrc** [comment]
works today
